# -*- coding: utf-8 -*-
"""project3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17r4ATN_QMZ7tqHg5mih5oToxUfLm6Eu7
"""

import numpy as np
import pandas as pd

data = {
    "EmployeeID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["Finance", "IT", "IT", np.nan, "Finance"],
    "Salary": [70000, np.nan, 80000, 90000, 75000],
    "HireDate": ["2018-05-01", "2019-06-15", "2020-07-20", "2021-01-10", "2019-11-30"],
    "RemoteWork": [True, False, True, False, np.nan],
    "Skills": [
        ["Excel", "Tableau"],
        ["Java", "AWS"],
        ["Python", "ML", "SQL"],
        None,
        ["Excel", "PowerBI"]
    ],
    "Performance": [{"2022": "A", "2023": "B"}, {"2022": "C"}, None, {"2022": "B", "2023": "A"}, {"2022": "A"}]
}

data

"""Just check the data"""

def Clean_data(data):
  for i,j in data.items():
    print(i,"::",j)

new=Clean_data(data)
print(new)

"""now actual use case in you need to clean data means remove None,Nan and after clean you need to add this data into one new dictionary"""

import pandas as pd

def clean_data(data):
    cleaned_dict = {}
    for key, values in data.items():
        cleaned_list = []
        for value in values:
            # keep only values that are not missing
            if not pd.isna(value):
                cleaned_list.append(value)
        cleaned_dict[key] = cleaned_list
    return cleaned_dict

new=Clean_data(data)

print(new)

"""Use case 2 Calculate avg salary"""

def calculate_avg_salary(data):
    # Step 1: Create one dictionary for department salary totals & counts
    department_salary = {}

    for dept, sal in zip(data["Department"], data["Salary"]):
        # Step 2: Add or update totals
        if dept not in department_salary:
            department_salary[dept] = {"total": sal, "count": 1}
        else:
            department_salary[dept]["total"] += sal
            department_salary[dept]["count"] += 1

    # Step 3: Calculate average using same dictionary (no new one)
    for dept in department_salary:
        total = department_salary[dept]["total"]
        count = department_salary[dept]["count"]
        department_salary[dept]["avg"] = total / count

    return department_salary

avg=calculate_avg_salary(data)
print(avg)

f="i love virat kolhi"
def frq(f):
  virat={}
  for i in f:
    if i in virat:
      virat[i]+=1
    else:
      virat[i]=1
  return virat

from google.colab import drive
drive.mount('/content/drive')

rohit=frq(f)
print(rohit)

import math

def find_missing_info_dynamic(data):
    missing_employees = []

    for i in range(len(data["Name"])):
        for col, values in data.items():
            value = values[i]

            if value is None or (isinstance(value, float) and math.isnan(value)):
                missing_employees.append(data["Name"][i])
                break

    return missing_employees

missing=find_missing_info_dynamic(data)
print(missing)

