# -*- coding: utf-8 -*-
"""Project2_Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9V1F18XFMDP2R95kc5JJKKTB2HrC2kN
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col,udf,greatest
from pyspark.sql.types import StringType,BooleanType,IntegerType


# Create or get existing Spark session
spark = SparkSession.builder \
    .appName("Students_data") \
    .getOrCreate()

df=spark.read.csv("/content/employee_performance_dirty.csv",header=True,inferSchema=True)

"""Use Case 1 — Data Cleaning (no return, performs action)

Goal:
Clean the dataset by replacing junk or null values (like "NaN", "missing", "junk") with None or mean value.

Function Type:
➡️ Function with arguments, no return

Why:

You’ll pass the DataFrame as an argument.

The function just performs cleaning inside the function itself (modifies DataFrame or prints result).
"""

from pyspark.sql.functions import col, when

def Clean_data_frame(df):
    for c in df.columns:
        df = df.withColumn(
            c,
            when((col(c) == "NaN") | (col(c) == "missing") | (col(c) == "junk"), None).otherwise(col(c))
        )
    df.show()

a=[1,2,3,4,5,6]

def rev_list(a):
  return a[::-1]

data = [
    ("Nilesh", 80, 75, 90),
    ("harshu", 60, 70, 65),
    ("rohit", 95, 88, 92)
]

columns = ["name", "math_marks", "science_marks", "english_marks"]
df = spark.createDataFrame(data, columns)

def show_student_marks(df):
    subject_cols = [c for c in df.columns if c.endswith("_marks")]
    df.select("name", *subject_cols).show()

show_student_marks(df)

students = [
    {"name": "Nilesh", "math_marks": 80, "science_marks": 75, "english_marks": 90},
    {"name": "Harshu", "math_marks": 60, "science_marks": 70, "english_marks": 65},
    {"name": "Rohit", "math_marks": 95, "science_marks": 88, "english_marks": 92}
]

"""**we use orint here coz we dont need to return anything here just we need to print the name and marks **"""

def show_student_marks(students):
    for s in students:
        print(f"Name: {s['name']}, Marks: {s['math_marks']}, {s['science_marks']}, {s['english_marks']}")

show_student_marks(students)

"""**Calculate Marks it means we need to return Something so we use return in this function**"""

def calculate_total_marks(students):
  for c in students:
    c["Total_marks"]=c["math_marks"] + c["science_marks"] + c["english_marks"]
    return students

calculate_total_marks(students)
print(students)

"""Now we need to find the avg so we need to return something so use return"""

def calculate_average_marks(students):
    for s in students:
        s["average_marks"] = s["total_marks"] / 3   # same key name
    return students

students = calculate_average_marks(students)

def display(name,marks):
  print("name of student",name)
  print("marks of student",marks)

def Total_marks(marks):
  return sum(marks)

def cal_avg(marks):
  return sum(marks)/len(marks)

def show_student_marks():
    name="nilesh","harshu"
    marks=[55,60,70]
    total=Total_marks(marks)
    cal=cal_avg(marks)

    dis=display(name,marks)
    print(dis)
    print("Totals is",total,"calculate avg",cal)

show_student_marks()

4/5

4//5

def addition(a,b):

  return a+b

def substraction(a,b):
  return a-b

def divide(a,b):
  return a/b

def multiplication(a,b):
  return a*b
def main():
    # call each function and store its return value
    add_result = addition(4, 5)
    sub_result = substraction(10, 3)
    div_result = divide(20, 4)
    mul_result = multiplication(6, 7)

    # print results
    print("Addition of two numbers:", add_result)
    print("Subtraction of two numbers:", sub_result)
    print("Division of two numbers:", div_result)
    print("Multiplication of two numbers:", mul_result)
if __name__ == "__main__":
    main()

employees_dirty = [
    {"id": "001", "name": "   nilesh ", "age": "29", "department": "Data", "salary": "75000", "joining_date": "2019-04-10"},
    {"id": "002", "name": "Ravi", "age": "NaN", "department": "data", "salary": "72000", "joining_date": "2018-06-20"},
    {"id": "003", "name": "Sneha", "age": 27, "department": "", "salary": None, "joining_date": "2020-11-15"},
    {"id": "004", "name": "Anjali", "age": -25, "department": "HR", "salary": "sixty thousand", "joining_date": "2017-03-01"},
    {"id": "005", "name": "Kiran", "age": 35, "department": "Finance", "salary": "90000", "joining_date": ""},
    {"id": "006", "name": "Ravi", "age": "30", "department": "DATA", "salary": "72000", "joining_date": "2018-06-20"},  # duplicate
    {"id": "007", "name": "", "age": 40, "department": "Finance", "salary": 88000, "joining_date": "NaN"},
    {"id": "008", "name": "Suresh", "age": None, "department": "IT", "salary": "100000", "joining_date": "2016-09-12"},
]

"""Use case 1.clean the data

"""

def CleanData(employees_dirty):
    clean = []  # new list to store cleaned records

    for emp in employees_dirty:
        record = emp.copy()  # make a copy so we don’t change original

        # --- Clean Name ---
        name = record.get("name", "").strip().capitalize()
        record["name"] = name if name != "" else "Unknown"

        # --- Clean Department ---
        dept = record.get("department", "").strip().upper()
        record["department"] = dept if dept != "" else "UNASSIGNED"

        # --- Clean Age ---
        try:
            age = int(record.get("age", 0))
            record["age"] = age if age > 0 else None
        except:
            record["age"] = None

        # --- Clean Salary ---
        salary = record.get("salary", None)
        try:
            record["salary"] = int(salary)
        except:
            # handle cases like "sixty thousand" or None
            record["salary"] = None

        # --- Clean Joining Date ---
        join_date = record.get("joining_date", "").strip()
        record["joining_date"] = join_date if join_date not in ["", "NaN", None] else "Unknown"

        # Add to cleaned list
        clean.append(record)

    # --- Remove Duplicates (based on 'id') ---
    unique = []
    seen_ids = set()
    for emp in clean:
        if emp["department"] not in seen_ids:
            unique.append(emp)
            seen_ids.add(emp["department"])

    return unique

data=CleanData(employees_dirty)
for Cleaned_data in data:
  print(Cleaned_data)

print(data)

"""Use case 2 Calculate AVG ...based on salary"""

def calculate_avg_salary(Cleaned_data):
  total=0
  count=0
  for i in Cleaned_data:
    if i["salary"] is not None:
      total+=i["salary"]
      count+=1
  return total /count if count > 0 else 0

avg=calculate_avg_salary(data)
print(avg)

"""Use case Oldest/Youngest Emp"""

def oldest_youngest(data):
    valid_employees = [emp for emp in data if emp.get("age") is not None]

    if not valid_employees:
        return None, None  # Return None for both if no valid ages are found

    oldest = max(valid_employees, key=lambda emp: emp["age"])
    youngest = min(valid_employees, key=lambda emp: emp["age"])

    return oldest, youngest

new_old_young=oldest_youngest(data)

print(new_old_young)

def salary_min_max(data):
    valid_employees = [emp for emp in data if emp.get("salary") is not None]

    if not valid_employees:
        return None, None  # Return None for both if no valid ages are found

    maximum = max(valid_employees, key=lambda emp: emp["salary"])
    minimum = min(valid_employees, key=lambda emp: emp["salary"])

    return maximum, minimum

cal=salary_min_max(data)
print(cal)

def find_critical(data):
  critical={}
  for dept in data:
    dept1=dept["department"]
    dept2=dept["salary"]
    if dept1 not in critical:
      critical[dept1]={"total_salary":0}
    if dept2 is not None:
      critical[dept1]["total_salary"]+=dept2

  return critical
    #critical[dept1]["sal"]+=1

dept2=find_critical(data)

print(dept2)

def FindMissingInfo(cleaned_data):
    missing = []  # list to store employees with missing info
    for emp in cleaned_data:
        # if either age or salary is missing
        if emp.get("age") is None or emp.get("salary") is None:
            missing.append(emp["name"])

    return missing

miss=FindMissingInfo(data)

print(miss)

print(data)

def search_name(data,name):
  found_list=[]
  for emp in data:
    if emp.get("name","").lower()==name.lower():
      found_list.append(emp)
  return found_list

data=CleanData(employees_dirty)   #we are calling cleanedData function coz we need updated cleaddata for that reasone

# Step 2: Take name input from user
name = input("Enter employee name to search: ")

result = search_name(data, name)

print(result)

